
const ActionTypes = {
	FETCH_USERS_DATA: 'FETCH_USERS_DATA',
	FETCH_USERS_SUCCESS: 'FETCH_USERS_SUCCESS',
	
	ADD_USER: 'ADD_USER',
	ADD_USER_SUCCESS: 'ADD_USER_SUCCESS',

	UPDATE_USER: 'UPDATE_USER',
	UPDATE_USER_SUCCESS: 'UPDATE_USER_SUCCESS',

	DELETE_USER: 'DELETE_USER',
	DELETE_USER_SUCCESS: 'DELETE_USER_SUCCESS',

	FETCH_TASKS_DATA: 'FETCH_TASKS_DATA',	
	FETCH_TASKS_SUCCESS: 'FETCH_TASKS_SUCCESS',

	ADD_TASK: 'ADD_TASK',
	ADD_TASK_SUCCESS: 'ADD_TASK_SUCCESS',
		
	UPDATE_TASK: 'UPDATE_TASK',
	UPDATE_TASK_SUCCESS: 'UPDATE_TASK_SUCCESS',
	
	DELETE_TASK: 'DELETE_TASK',
	DELETE_TASK_SUCCESS: 'DELETE_TASK_SUCCESS',

	START_LOADING: 'START_LOADING',
	END_LOADING: 'END_LOADING',
	EXPIRED_TOKEN:'EXPIRED_TOKEN'
}
export default ActionTypes;


